#!/bin/bash

#  I am _so_ going to burn in hell.
#  Read lines of values from arg 2 and store them in
#  the arrays of name <prefix>_<column>, using prefix passed in arg 1
#  and column names passed as args 3+
function _read_rows_from_value_lines() {
    local prefix="$1"
    local content="$2"
    shift 2
    local columns
    read -r -a columns <<< "$*"

    for column in "${columns[@]}"; do
        #echo "Scrubbing ${prefix}_${column}"
        unset "${prefix}_${column}"
    done

    local row_idx=0
    local column_idx=0
    local value
    while read value; do
        column=${columns[column_idx]}
        #  Ho hum, I gave up and used eval, couldn't get this working with $(())
        printf -v value "%q" "$value"
        eval "${prefix}_${column}[${row_idx}]=$value"

        column_idx=$((column_idx + 1))
        if [ "$column_idx" -ge "${#columns[*]}" ]; then
            column_idx=0
            row_idx=$((row_idx + 1))
        fi
        #echo "Column is $column, column_idx now $column_idx, row_idx now $row_idx"
    done <<< "$content"
}

#  Tests
results1="Assemblage 23
Naked (God Module RMX)
Addendum
2001
80
5:22
Ayria
Sapphire
Debris

100
6:14
Apoptygma Berzerk
Kathy's Song
Welcome To Earth \"Extra bit for testing\"

100
6:35"

results2="Colony 5
The Bottle
Lifeline

80
4:34"

echo -e "results1\n--------"
_read_rows_from_value_lines "track" "$results1" artist track album year rating tracktime
echo "track '${track_track[0]}', artist '${track_artist[0]}', album '${track_album[0]}'"
echo "track '${track_track[1]}', artist '${track_artist[1]}', album '${track_album[1]}'"
echo "track '${track_track[2]}', artist '${track_artist[2]}', album '${track_album[2]}'"

echo -e "\nresults2\n--------"
_read_rows_from_value_lines "track" "$results2" artist track album year rating tracktime
echo "track '${track_track[0]}', artist '${track_artist[0]}', album '${track_album[0]}'"
echo "track '${track_track[1]}', artist '${track_artist[1]}', album '${track_album[1]}'"
echo "track '${track_track[2]}', artist '${track_artist[2]}', album '${track_album[2]}'"
